### ISSUE TITLE
DeepSample program is throwing error org.pcap4j.core.PcapNativeException

### ISSUE THREAD

**Issue by vikasguptascs** [WojciechZankowski/iextrading4j-hist#2]
[data%2Ffeeds%2F20171104%2F20171104_IEXTP1_DEEP1.0.pcap.gz](https://github.com/WojciechZankowski/iextrading4j-hist/files/1590876/data.2Ffeeds.2F20171104.2F20171104_IEXTP1_DEEP1.0.pcap.gz)
Hi All,

Thanks for your support. I am looking for one small guidance/help.

I was trying to read Sample(PCAP format) file using below libraries and observed that it throws exception like below.
I was using api readDEEPsample() of DeepSample.java
**_iextrading4j-hist/iextrading4j-hist-samples/src/main/java/pl/zankowski/iextrading4j/hist/samples/DEEPSample.java_**

# **Exception:**
 org.pcap4j.core.PcapNativeException: pcap_open_offline_with_tstamp_precision is not supported by the pcap library installed in this environment.
	at org.pcap4j.core.Pcaps.openOffline(Pcaps.java:234)

	
# **Libraries used :**
iextrading4j-hist-api-1.0.0.jar
iextrading4j-hist-deep-1.0.0.jar
iextrading4j-hist-tops-1.0.0.jar
pcap4j-core-1.7.2.jar
pcap4j-packetfactory-static-1.7.2.jar

# 
**Sample pcap file :** 
data%2Ffeeds%2F20171104%2F20171104_IEXTP1_DEEP1.0.pcap.gz file which contains pcap file

# **Additional Info**
Pcaps.libVersion WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

### May I request you please to help me on this.

**thanks**
Vikas

**Comment by WojciechZankowski** [comment]
Hey,

I checked out the sample on my env and it is working without any issues. It seems like the problem is in the WinPcap library that you are using, it does not support this kind of timestamps. But even tho I tried with different timestamp settings and generally I cannot open it using WinPcap & pcap4j.

I am using Npcap on my env and if it is possible you should try to use it too. Npcap can be downloaded directly from their website:

https://nmap.org/npcap/

I am using version 0.93, but it will also work with the newest one. I will remove WinPcap from README, thanks for pointing this out! 

Let me know if it is acceptable solution for you?

Have a nice day,

Wojtek

**Comment by vikasguptascs** [comment]
Hi,

Thank you so much for quick response.

I will go with your suggestion and let you know if there is any issue i observe.

thanks again.
Have a nice day..


Regards,
Vikas

**Comment by vikasguptascs** [comment]
Hi,

I tried Solution but it failed with same exception.

I used Npcap library with version 0.97(latest).
I am getting same error.
## Exception 
org.pcap4j.core.PcapNativeException: pcap_open_offline_with_tstamp_precision is not supported by the pcap library installed in this environment.
	at org.pcap4j.core.Pcaps.openOffline(Pcaps.java:234)
	at RunPcap.readDEEPsample(RunPcap.java:30)
	at RunPcap.main(RunPcap.java:19)


My Configuration: 
:: Java 1.8
:: Window 7 OS
:: Created Standalone app in java to verify the features
:: List of supporting jars(Please find attachment)
:: Used same pcap file mentioned in previous conversation

Please do let me know if I can show you or if you need any details.

May I request you please to help me on this.

thanks.
![pcap project libs](https://user-images.githubusercontent.com/11174195/34414291-808dfc66-ec0e-11e7-994f-51c29be64f36.png)

**Comment by WojciechZankowski** [comment]
Pcap4j should show some logs, in my case it is like that, could you provide what you receive?

```
17:05:10.609 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.97, based on libpcap version 1.8.1
17:05:10.681 [main] INFO org.pcap4j.core.PcapHandle - Starting loop.
```

Thanks!

**Comment by vikasguptascs** [comment]
Hi ,

Thanks for response.

It failed immediately with below exception 

**org.pcap4j.core.PcapNativeException: pcap_open_offline_with_tstamp_precision is not supported by the pcap library installed in this environment.
	at org.pcap4j.core.Pcaps.openOffline(Pcaps.java:234)
	at RunPcap.readDEEPsample(RunPcap.java:30)
	at RunPcap.main(RunPcap.java:19)**

I am attaching zip file (contain java file
[## RunPcap.java.zip](https://github.com/WojciechZankowski/iextrading4j-hist/files/1591586/RunPcap.java.zip)
)which i am using to run

Could you please help me on this.
I can share my screen with you or we can talk in case of more details.

**Comment by vikasguptascs** [comment]
I have created standalone application.

in my case, it did not generate output like 
17:05:10.609 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.97, based on libpcap version 1.8.1

**Comment by vikasguptascs** [comment]
`May I know what value you are passing in  Pcaps.openOffline() method ?

**Comment by vikasguptascs** [comment]
May I know what value you are passing in  Pcaps.openOffline() method ?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

*?*With Best Regards,
 Vikas Gupta
+*91-9910490182*

**Comment by WojciechZankowski** [comment]
I think it still cannot find pcap library, did you install Npcap with WinPcap API-compatible mode? Please do following:

1. Uninstall Npcap (by default it is installed in C:/Program Files/Npcap)
2. During Npcap installation select checkbox "Install with WinPcap API-compatible mode" or sth like that, it should be the last checkbox.


I am passing path to pcap file ;)

**Comment by vikasguptascs** [comment]
Thanks for your support . I am trying now.

**Comment by vikasguptascs** [comment]
Thanks alot!! . I appreciate your support.

There are two main resolution for this.
1) Use Npcap llibrary
2) During installation of Npcap, select checkbox "Install with WinPcap API-compatible mode"

Again thanks for your time.

**Comment by WojciechZankowski** [comment]
So it is working, right?

**Comment by vikasguptascs** [comment]
yes , its working now.. thanks again..

One last confirmation i need,
What if i want to run same program in linux, Do i need to do any kind of checkbox selection while installing npcap lib?
Do i need to do some more steps ?

**Comment by WojciechZankowski** [comment]
I have not tried to run it on Linux, probably checkbox is not needed.

Good to hear your problem is solved.
