### ISSUE TITLE
Issue : Some of Deeps/Tops History data is failed to read

### ISSUE THREAD

**Issue by vikasguptascs** [WojciechZankowski/iextrading4j-hist#3]
Hi All,

Thanks for your support. 

During parsing Deeps/Tops History data , There are mixed of a reading response. Some of data has been parsed and some of them got failed. 
**[](I have attached complete response of execution of Tops pcap file
[TopsResponse.docx](https://github.com/WojciechZankowski/iextrading4j-hist/files/1591993/TopsResponse.docx))**
. **I have highlighted error red color.**

I am referring to DeepSample/TopsSample code from https://github.com/WojciechZankowski/iextrading4j-hist 

I have tried this tops data(in gz format) attached here and got an issue.
[data%2Ffeeds%2F20171104%2F20171104_IEXTP1_TOPS1.6.pcap.gz](https://github.com/WojciechZankowski/iextrading4j-hist/files/1591998/data.2Ffeeds.2F20171104.2F20171104_IEXTP1_TOPS1.6.pcap.gz)

## May I request you please to help me on this. Please guide me how to handle such error.
Do i need to write our own wrapper class on open source library to tackle such error ?

thanks,
Vikas

**Comment by vikasguptascs** [comment]
Hi Team,

May I request you please to provide me any update on the issue

**Comment by vikasguptascs** [comment]
Hi Team,

Please do let me know if you need any clarification or further detail about issue .
I would be happy to answer.

Thanks,
Vikas

**Comment by WojciechZankowski** [comment]
Hi, 

Currently TOPS v1.6 is not supported in the library. 

Supported specification: 

TOPS version 1.56 - May 9, 2017
DEEP version 1.04 - August 1, 2017

I can add support for version 1.6 in the following days. I will also add option to handle errors on client side. 

Cheers!

**Comment by vikasguptascs** [comment]
Hi All,

Thanks for your response.

Could you please comment on  my understanding 
1)  current library supports only Deep V1.0 and Tops V1,5.  It does not support Tops v1.6 right now. i am referring this (https://iextrading.com/trading/market-data/#hist-download) 
2) its causing exception just because it does not support Tops v1.6 .
3) when we can expect support for Tops v1.6 and exception handling will be implemented?

May I request you please to update me on this.

Thanks a lot for your support.

thanks,
Vikas

**Comment by WojciechZankowski** [comment]
Hi,

1. Yes
2. Yes
3. Yes, it should be available tomorrow!

Have a nice day!

**Comment by vikasguptascs** [comment]
Hi ,

Thanks for your quick response. 

Request you to update me with latest version of code once implemented so that i can use. 

Thanks again.

**Comment by WojciechZankowski** [comment]
Hi again,

New version is available. It supports TOPS 1.6.  Go check it out ;) 

Let me know if it works for you!

Cheers!

**Comment by vikasguptascs** [comment]
Hi,

Thanks alot for your quick resolution. 
Surely i will check and let you know in case of any issue.

Could you please confirm that option of handling exception at client side is added ?

Many Thanks,
Vikas

**Comment by vikasguptascs** [comment]
Hi ,

Please also upload jar in maven repository as its currently available 1.0,0
https://mvnrepository.com/artifact/pl.zankowski/iextrading4j-hist-deep

thanks again.

Many Thanks,
Vikas
