### ISSUE TITLE
ERROR [org.pcap4j.core.PcapHandle] :: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by vikasguptascs** [WojciechZankowski/iextrading4j-hist#5]
Hi All,

https://api.iextrading.com/1.0/hist?date=20171117 

During parsing PCAP data using open source pcap4j library, i am getting Error "java.lang.OutOfMemoryError: GC overhead limit exceeded".
I have attached complete Error Stack trace here  as attachment.

My System configuration details :
RAM 8 GB
HardDisk 500 GB

There is no more process running in my system which consumes my hardware resources. but still i am getting same error. 

I also restarted system , thinking that it might be intermittent issue but it keeps coming. 

Kindly help me on this. 

thanks
[GCError.txt](https://github.com/WojciechZankowski/iextrading4j-hist/files/1660442/GCError.txt)

**Comment by vikasguptascs** [comment]
Hi Team,


Could you please provide any updates on this concern.

thanks

**Comment by WojciechZankowski** [comment]
Hey,

It is an issue with pcap4j library. Actually I cannot help with that in any way. 

Cheers,

Wojtek
