### ISSUE TITLE
packet.getPayload() returns null

### ISSUE THREAD

**Issue by polarisgt** [WojciechZankowski/iextrading4j-hist#8]
import org.pcap4j.core.*;
import org.pcap4j.packet.Packet;
import pl.zankowski.iextrading4j.hist.api.message.IEXSegment;
import pl.zankowski.iextrading4j.hist.deep.IEXDEEPMessageBlock;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.zip.GZIPInputStream;

public class IexDeepReader {
    public static File unGzip(File infile, boolean deleteGzipfileOnSuccess) throws IOException {
        GZIPInputStream gin = new GZIPInputStream(new FileInputStream(infile));
        FileOutputStream fos = null;
        try {
            File folder = new File("temp");
            if (!folder.isDirectory())
                folder.mkdirs();

            File outFile = new File(folder, infile.getName().replaceAll("\\.gz$", ""));
            if (outFile.isFile())//already exists
                return outFile;

            fos = new FileOutputStream(outFile);
            byte[] buf = new byte[100000];
            int len;
            while ((len = gin.read(buf)) > 0) {
                fos.write(buf, 0, len);
            }

            fos.close();
            if (deleteGzipfileOnSuccess) {
                infile.delete();
            }
            return outFile;
        } finally {
            if (gin != null) {
                gin.close();
            }
            if (fos != null) {
                fos.close();
            }
        }
    }

    private void readDEEPsample() throws PcapNativeException, InterruptedException, NotOpenException, IOException {
        String filename = "data%2Ffeeds%2F20180628%2F20180628_IEXTP1_DEEP1.0.pcap.gz";
        PcapHandle handle = Pcaps.openOffline(unGzip(new File(filename), false).getPath(),
                                              PcapHandle.TimestampPrecision.NANO);

        handle.loop(-1, new PacketListener() {
            @Override
            public void gotPacket(Packet packet) {
                byte[] data = packet.getPayload().getPayload().getPayload().getRawData();
                IEXSegment block = IEXDEEPMessageBlock.createIEXSegment(data);
                System.out.println(block);
            }
        });

        handle.close();
    }

    public static void main(String[] args) {
        IexDeepReader reader = new IexDeepReader();
        try {
            reader.readDEEPsample();
        } catch (PcapNativeException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (NotOpenException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

**Comment by polarisgt** [comment]
It probably has something to do with not having Npcap/pcap4j configured properly. Any information I can find?

**Comment by WojciechZankowski** [comment]
Hello,

I will take a look and back to you in minutes!

Cheers,

Wojtek

**Comment by WojciechZankowski** [comment]
So to make it work you need to install some Pcap library in your system. From Readme:

> To run samples it is required to have pcap library (Npcap recommended) installed on computer. 

If you are running application on Windows then I can recommend this one: https://nmap.org/npcap/ because I use it personally and it work flawless!

**Comment by WojciechZankowski** [comment]
Also please use the newest version released couple minutes ago so you are sure that all messages are parsed correctly, thank you!

```java
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-hist-all</artifactId>
	<version>1.2.0</version>
</dependency>
```

Please let me know if this fixed your problem.

**Comment by polarisgt** [comment]
Thanks for the info. I'm on Ubuntu.

**Comment by polarisgt** [comment]
Further digging:
packet.getRawData() does provide meaningful content. So I figure pcap4j is working all right. Pcap4j version is 1.7.3(Is it not good?).

packet.getPayload() returns null due to the packet type being UnknownPacket which has null-returning getPayload() function defined in AbstractPacket.class.

**Comment by polarisgt** [comment]
Solved! Had to include pcap4j-packetfactory-static in project otherwise I guess pcap4j is running sort of empty shell.

**Comment by WojciechZankowski** [comment]
Good! Thank you for information, hope you will have no issues with the parser!

**Comment by polarisgt** [comment]
Excellent work indeed!
